config/routes.rb
Rails.application.routes.draw do
  resources :surveys do 
    collection do
      get  :generate
      post :generate
      get  :pdf
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/survey.rb
class Survey < ApplicationRecord
  include MicroservicesEngine

  has_many :survey_trip_stops, dependent: :destroy
  accepts_nested_attributes_for :survey_trip_stops

  validates :date, presence: true
  validates :shift, presence: true

  def formatted_date
    date.strftime '%A, %B %e, %Y'
  end

  def location
    survey_trip_stops.order(:sequence_number).first.location
  end

  def time
    date.strftime '%-H:%M %P'
  end

  def self.generate_ntd(start_date:, end_date:, daily_count:)
    trip_result = MicroservicesEngine.get(
      :trips, [:generate_random_trips], { start_date: start_date,
                                        end_date: end_date,
                                        count_per_day: daily_count })
    JSON.parse(trip_result).fetch('trips').each do |trip_data|
      survey_attributes = {
        date: DateTime.iso8601(trip_data.fetch('datetime')).in_time_zone,
        shift: trip_data.fetch('shift'),
        in_house: false
      }
      survey = Survey.create! survey_attributes
      trip_data.fetch('trip_stops').each do |stop_data|
        stop_attributes = {
          miles_from_previous: stop_data.fetch('feet_from_previous_stop') / 5280.0,
          time: DateTime.iso8601(stop_data.fetch('datetime')).in_time_zone, # TODO: see r3#2483
          sequence_number: stop_data.fetch('sequence_number').to_i,
          location: stop_data.fetch('location').fetch('name'),
          survey: survey
        }
        SurveyTripStop.create! stop_attributes
      end
    end
  end
end

app/models/survey_trip_stop.rb
class SurveyTripStop < ApplicationRecord
  belongs_to :survey

  validates :location, presence: true
  validates :time, presence: true

  def formatted_time
    time.strftime('%H:%M')
  end

  def date
    time.strftime('%m/%d/%Y')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :find_survey, only: %i(destroy show update)

  def destroy
    if @survey.destroy
      flash[:notice] = 'Successfully deleted survey.'
    else
      flash[:alert] = @survey.errors.full_messages
    end
    redirect_to surveys_path(page: cookies[:page],
                             completed: cookies[:completed])
  end

  def generate
    if request.get?
      @default_start = 1.month.since.beginning_of_month
      @default_end = 1.month.since.end_of_month
    else
      generation_result = 
        case params.require(:type)
        when 'ntd'
          Survey.generate_ntd(
            start_date: params.require(:start_date),
            end_date: params.require(:end_date),
            daily_count: params.require(:daily_count)
          )
        when 'in_house' #TODO
        end
      #TODO: handle failure
      flash[:notice] = 'Successfully generated surveys.'
      redirect_to surveys_path
    end
  end

  def index
    params[:page] = 1 if params[:page] == ''
    @completed = params[:completed] == 'true'
    @surveys = Survey.where(completed: @completed)
                     .paginate(page: params[:page], per_page: 25)
    cookies[:page] = params[:page]
    cookies[:completed] = @completed
  end

  def pdf
    surveys = Survey.find(params[:surveys]).sort_by(&:date)
    surveys.each { |survey| survey.update printed: true }
    pdf = SurveyPdf.new(surveys)
    send_data pdf.render, filename: "Survey #{DateTime.current}.pdf",
                          type: 'application/pdf', disposition: 'inline'
  end

  def update
    if @survey.update survey_params
      flash[:notice] = 'Successfully updated survey.'
    else
      flash[:alert] = @survey.errors.full_messages
    end
    redirect_to surveys_path(page: cookies[:page],
                             completed: cookies[:completed])
  end

  private

  def find_survey
    @survey = Survey.find_by id: params.require(:id)
    # render public/404 unless @survey.present?
  end

  def survey_params
    params.require(:survey).permit(:starting_pax, :completed,
                                   survey_trip_stops_attributes: [:id, :boarded,
                                                                  :alighted])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Surveys
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/surveys/generate.haml
%h1 Generate Surveys

= form_tag generate_surveys_path(type: :ntd) do
  Generate random NTD surveys:
  .field
    = label_tag :start_date, 'Starting on:'
    = text_field_tag :start_date, @default_start.strftime('%-m/%-d/%Y'), class: 'day-pick'
  .field
    = label_tag :end_date, 'Ending on:'
    = text_field_tag :end_date, @default_end.strftime('%-m/%-d/%Y'), class: 'day-pick'
  .field
    = label_tag :daily_count, 'Surveys per day:'
    = number_field_tag :daily_count, 3, min: 0, step: 1
  .actions= submit_tag 'Generate NTD surveys'

= #TODO: in-house surveys

app/views/surveys/index.haml
%h1 Surveys

= link_to 'Generate surveys', generate_surveys_path

- if @completed
  = link_to 'View incomplete surveys', surveys_path(completed: false)
- else
  = link_to 'View completed surveys', surveys_path(completed: true)
= will_paginate @surveys
= form_tag pdf_surveys_path, method: :get do |form|
  %table#index-table
    %thead
      %tr
        %th Survey #
        %th Date
        %th Shift
        %th Time
        %th Starting Passengers
        %th Printed?
        %th In House?
        %th
        %th
        %th 
          Print
          = check_box_tag 'select-all'
    %tbody
      - @surveys.each do |survey|
        %tr
          %td= survey.id
          %td= survey.formatted_date
          %td= survey.shift
          %td= survey.time
          %td= survey.starting_pax
          %td
            - if survey.printed
              Yes
            - else
              No
          %td
            - if survey.in_house
              Yes
            - else
              No
          %td= link_to 'View', survey_path(survey.id)
          %td= link_to 'Delete', survey_path(survey.id), method: :delete
          %td= check_box_tag 'surveys[]', survey.id, false, class: 'print-survey'
  = submit_tag 'Print selected surveys', disabled: true, id: 'submit'

app/views/surveys/show.haml
%h1  Survey ##{@survey.id}
%p Date: #{@survey.formatted_date}
%p Shift: #{@survey.shift}
%p Time: #{@survey.time}
= form_for @survey do |survey_form|
  .field
    = survey_form.label 'Starting Passengers: '
    = survey_form.number_field :starting_pax
  %table
    %thead
      %tr
        %th Time
        %th Location
        %th Passengers Boarded
        %th Passengers Alighted
        %th
    %tbody
      = survey_form.fields_for :survey_trip_stops do |sts_form|
        %tr
          %td= sts_form.object.time.strftime '%H:%M %P'
          %td= sts_form.object.location
          %td= sts_form.number_field :boarded
          %td= sts_form.number_field :alighted
  .field= survey_form.hidden_field :completed, value: true
  .actions= survey_form.submit "Update Counts and Mark as Completed"
  - if cookies[:page].present?
    = link_to "Back", surveys_path(page: cookies[:page], completed: cookies[:completed])
  - else
    = link_to "Back", surveys_path(completed: cookies[:completed])